### ISSUE TITLE
Unhandled exception if a ref name including UTF-8 non-breaking space exists

### ISSUE THREAD

**Issue by hasturkun** [stacked-git/stgit#111]
Encountering non-breaking space characters (0xc2 0xa0) in existing refs' names causes an unhandled exception for `stg init` and `stg branch -c`.
It looks like the regexp `re.match(r'^([0-9a-f]{40})\s+(\S+)$', line)` doesn't match due to the sequence C2A0 in the ref name being an NBSP.

Reproduction case:
```
$ git init && echo foo > foo && git add foo && git commit -m initial
$ git update-ref "refs/prefetch/origin/foo"$'\xc2\xa0'"bar" master
$ stg init
Error: Unhandled exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/stgit/main.py", line 182, in _main
    ret = command.func(parser, options, args)
  File "/usr/lib/python3/dist-packages/stgit/commands/init.py", line 39, in func
    Stack.initialise(directory.repository)
  File "/usr/lib/python3/dist-packages/stgit/lib/stack.py", line 378, in initialise
    branch = Branch(repository, name)
  File "/usr/lib/python3/dist-packages/stgit/lib/git/branch.py", line 17, in __init__
    self.head
  File "/usr/lib/python3/dist-packages/stgit/lib/git/branch.py", line 31, in head
    return self.repository.refs.get(self._ref)
  File "/usr/lib/python3/dist-packages/stgit/lib/git/repository.py", line 77, in get
    self._ensure_refs_cache()
  File "/usr/lib/python3/dist-packages/stgit/lib/git/repository.py", line 55, in _ensure_refs_cache
    sha1, ref = m.groups()
AttributeError: 'NoneType' object has no attribute 'groups'

```
Version:
Stacked GIT 1.1-7-gb946-dirty
git version 2.32.0
Python version 3.5.2

(I should note that local changes in my version are all for local packaging, no changes to the code)

**Comment by jpgrayson** [comment]
Thank you @hasturkun for this issue report. This issue is repaired in d46a1fa.
