### ISSUE TITLE
1.4: `stg uncommit` fails with commit messages containing `*` characters

### ISSUE THREAD

**Issue by lkraav** [stacked-git/stgit#176]
With commit log like

```
...
* 2017aa241 - chore: phpcbf SlevomatCodingStandard.Namespaces.*FullyQualified.* (16 minutes ago) <leho>
...
```
we get this crash

```
$ stg uncommit 
Uncommitting 1 patches ... 
  Error: Unhandled exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/stgit/main.py", line 183, in _main
    return command.func(parser, options, args)
  File "/usr/lib/python3.9/site-packages/stgit/commands/uncommit.py", line 151, in func
    pn = stack.patches.make_name(c.data.message_str, disallow=taken_names)
  File "/usr/lib/python3.9/site-packages/stgit/lib/stack.py", line 204, in make_name
    assert self.is_name_valid(long_name)
AssertionError
```

**Comment by jpgrayson** [comment]
Hi @lkraav. Thank you for this issue.

I was able to reproduce this issue with v1.4 and HEAD. The minimum reproducing case I could come up with was:

```
$ stg new -m "a:.b.:"
Error: Unhandled exception:
Traceback (most recent call last):
  File "/home/jpgrayson/code/stgit/stgit/main.py", line 183, in _main
    return command.func(parser, options, args)
  File "/home/jpgrayson/code/stgit/stgit/commands/new.py", line 117, in func
    name = stack.patches.make_name(cd.message_str)
  File "/home/jpgrayson/code/stgit/stgit/lib/stack.py", line 204, in make_name
    assert self.is_name_valid(long_name), long_name
AssertionError: a-.b.
```

This kind of issue was partially affected/repaired after v1.4 by 247c93ca48fdbecf13ba105a47ea80398eea550d and 48d73dc79bd6433166a9a7437bca595bd05ea1aa, but obviously not completely repaired.

I've got comprehensive repair in the works.
