### ISSUE TITLE
Spelling mistake in mail.py causes stg mail to fail

### ISSUE THREAD

**Issue by dhowells** [stacked-git/stgit#178]
In stgit/commands/mail.py on line 668 it says:

            message_str = stack.patchs[pn].data.message_str

I think this should be:

            message_str = stack.patches[pn].data.message_str

This causes the following abort when I try to mail some patches:

Error: Unhandled exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/stgit/main.py", line 183, in _main
    return command.func(parser, options, args)
  File "/usr/lib/python3.10/site-packages/stgit/commands/mail.py", line 853, in func
    msg_id = __send_message('cover', tmpl, options, patches)
  File "/usr/lib/python3.10/site-packages/stgit/commands/mail.py", line 415, in __send_message
    msg = __build_cover(tmpl, msg_id, options, patches)
  File "/usr/lib/python3.10/site-packages/stgit/commands/mail.py", line 668, in __build_cover
    message_str = stack.patchs[pn].data.message_str
AttributeError: 'Stack' object has no attribute 'patchs'

**Comment by jpgrayson** [comment]
Thank you for reporting this, @dhowells. I've pushed a repair.
