### ISSUE TITLE
"stg import" allows import with same name as existing patch

### ISSUE THREAD

**Issue by chucklever** [stacked-git/stgit#64]
This happened recently and I have not tried to reproduce it but thought it would be good to note it here.

I had a patch in the current branch called "diff". I also had a patch file called /tmp/diff. Without thinking, I used "stg import /tmp/diff" to pull that patch file into the current branch.

The result was two patches in the same branch called "diff". Subsequently, normal stg operations resulted in a Python exception.

To recover, I edited the branch's unapplied file and removed the second "diff".

To prevent stgit metadata corruption from happening, "stg import" could:

- Fail to import the patch file
- Select a distinct name for the imported patch (eg, "diff2")
- Create a new branch and use the expected patch name

**Comment by chucklever** [comment]
I managed to do this to myself again. I captured the traceback this time.

```
[cel@klimt nfs-utils]$ stg edi
Invoking the editor: "/usr/bin/vim .stgit-edit.txt" ... done
Error: Unhandled exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/stgit/main.py", line 193, in _main
    ret = command.func(parser, options, args)
  File "/usr/lib/python3.8/site-packages/stgit/commands/edit.py", line 207, in func
    return trans.run(iw)
  File "/usr/lib/python3.8/site-packages/stgit/lib/transaction.py", line 280, in run
    log_entry(self.stack, msg)
  File "/usr/lib/python3.8/site-packages/stgit/lib/log.py", line 375, in log_entry
    new_log = LogEntry.from_stack(last_log, stack, msg)
  File "/usr/lib/python3.8/site-packages/stgit/lib/log.py", line 179, in from_stack
    patches=dict(
  File "/usr/lib/python3.8/site-packages/stgit/lib/log.py", line 180, in <genexpr>
    (pn, stack.patches.get(pn).commit) for pn in stack.patchorder.all
  File "/usr/lib/python3.8/site-packages/stgit/lib/stack.py", line 229, in get
    return self._patches[name]
  File "/usr/lib/python3.8/site-packages/stgit/lib/objcache.py", line 16, in __getitem__
    self.__objects[name] = self.__create(name)
  File "/usr/lib/python3.8/site-packages/stgit/lib/stack.py", line 216, in create_patch
    p.commit  # raise exception if the patch doesn't exist
  File "/usr/lib/python3.8/site-packages/stgit/lib/stack.py", line 37, in commit
    return self._stack.repository.refs.get(self._ref)
  File "/usr/lib/python3.8/site-packages/stgit/lib/git/repository.py", line 74, in get
    return self._repository.get_commit(self._refs[ref])
KeyError: 'refs/patches/master/diff'
[cel@klimt nfs-utils]$
```

**Comment by chucklever** [comment]
I downloaded an mbox file containing one cover letter and three patches. Then:

```
[cel@manet linux]$ stg import -m /tmp/mbox
Checking for changes in the working directory ... done
Importing patch "mbox" ... 
  Warning: No diff found, creating empty patch
  Now at patch "mbox"
done
Importing patch "mbox" ... done
Importing patch "mbox" ... done
Importing patch "mbox" ... done
[cel@manet linux]$ stg se -s
+ mbox
+ mbox
+ mbox
> mbox
[cel@manet linux]$ 
```

It created four patches with the exact same name! To avoid stack corruption, I immediately deleted all four new patches with "stg undo --hard" (times four).

"stg import" has got to get smarter about how it chooses patch names. In this case, the mbox contains Subject: fields that can be used to generate reasonable and unique patch names. In other cases, "stg import" might do the same thing "stg new" does.

**Comment by jpgrayson** [comment]
I appreciate this issue report @chucklever. And I think I have it repaired in 0e569fd. Closing.
