### ISSUE TITLE
`stg pull` on a branch without upstream set is causing an Exception

### ISSUE THREAD

**Issue by NonLogicalDev** [stacked-git/stgit#83]
If a particular branch does not have tracking information spits out traceback.

```
Traceback (most recent call last):
  File "/Users/<USER>/Documents/Developer/stgit/stgit/main.py", line 188, in _main
    ret = command.func(parser, options, args)
  File "/Users/<USER>/Documents/Developer/stgit/stgit/commands/pull.py", line 137, in func
    pull(repository, remote_name)
  File "/Users/<USER>/Documents/Developer/stgit/stgit/commands/pull.py", line 78, in pull
    runner.returns([0, 1]).run()
  File "/Users/<USER>/Documents/Developer/stgit/stgit/run.py", line 265, in run
    self._run_noio()
  File "/Users/<USER>/Documents/Developer/stgit/stgit/run.py", line 161, in _run_noio
    self._prep_cmd(),
  File "/Users/<USER>/Documents/Developer/stgit/stgit/run.py", line 88, in _prep_cmd
    return [fsencode_utf8(c) for c in self._cmd]
  File "/Users/<USER>/Documents/Developer/stgit/stgit/run.py", line 88, in <listcomp>
    return [fsencode_utf8(c) for c in self._cmd]
  File "/Users/<USER>/Documents/Developer/stgit/stgit/compat.py", line 28, in fsencode_utf8
    return os.fsencode(s)
  File "/usr/local/opt/python@3.8/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 806, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by NonLogicalDev** [comment]
@jpgrayson this is a fairly straightforward fix
